### ISSUE TITLE
Reset of the Counter

### ISSUE THREAD

**Issue by Jacke87** [derAlff/ioBroker.ve#11]
The reset of the counters is taken into account when restarting

**Comment by derAlff** [comment]
What do you mean?

**Comment by Jacke87** [comment]
When I restart Venuso's, all energy counters are reset.Therefore, I save all meter readings using a script in Iobroker between.For example, I fed 100kWh from the Battery to the Acout, after restarting this counter is to zero. The script notices it, stores the 100 kWh in a marker and adds the new one Note reading.

**Comment by derAlff** [comment]
Ok, that's a nice information 👍

I think, I implement it so, that you don't miss meter data.

Do you have some code for me?

**Comment by derAlff** [comment]
No code as respone.
Closed.
