### ISSUE TITLE
Please consider adding this adapter to ioBroker repositories

### ISSUE THREAD

**Issue by mcm1957** [derAlff/ioBroker.ve#21]
Please consider adding your adapter to (latest) Repository if it is working for users.

See https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository-web-frontend

**Comment by derAlff** [comment]
Hello and thank you for your message.

I was planning to publish this adapter to the ioBroker repository! However, I am working on this project alone. Time is scarce as I also work as a professional programmer during the day. In addition, there are other small leisure projects and an illness that further limit my time. I work on this project as often as I can, but progress is slow.

I would like to upload a properly tested adapter to the repository. Unfortunately, this is not the case at the moment.

Please see my other ioBroker adapter (it is on repository ;) ) -> [ioBroker.signal-cmb](https://github.com/derAlff/ioBroker.signal-cmb)

Thank you very much!
