### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by Stroell** [derAlff/ioBroker.ve#23]
Hi,
vielen Dank für den Adapter. Leider funktioniert er bei mir nicht richtig. Wenn ich ihn starte erhalte ich sofort folgende Fehlermeldungen:
![image](https://github.com/derAlff/ioBroker.ve/assets/42348774/bca1f4d5-1460-4f6c-9f43-7a9e13d47f75)
![image](https://github.com/derAlff/ioBroker.ve/assets/42348774/606caa4d-30c6-4a73-b1d2-a4238bf4d5f3)

Danach stürzt der Adapter immer ab.
Kann ich irgendetwas tun? 
Folgende Werte schafft er aber zu bekommen, leider nicht regelmäßig.
![image](https://github.com/derAlff/ioBroker.ve/assets/42348774/5367edc8-f3d0-4638-8243-91e2e9053c0b)

**Comment by derAlff** [comment]
Ich denke, deine Node Version ist zu alt.
Update bitte deinen ioBroker komplett und versuche es nocheinmal.
Ich habe gerade eben mit Node Version v20.14.0 alles erneut getestet und alles funktioniert.

Gib bitte eine Rückmeldung.

Danke dir
